### ISSUE TITLE
Clicking Submit after changing date in "make booking" page causes error 

### ISSUE THREAD

**Issue by raniarazak** [natebakescakes/team11-cab#49]
1. If we want to select a different date in make booking page, the calendar always defaults to December 1927.
2. Clicking submit after selecting the date we want causes page to break.
3. The format of date changes when we go from Home page (mm/dd/yy) to Make Booking page (yy/mm/dd).

<img width="957" alt="error1" src="https://user-images.githubusercontent.com/19702763/41495368-0f197658-7158-11e8-892d-bdc53e1425b3.png">
<img width="957" alt="error2" src="https://user-images.githubusercontent.com/19702763/41495369-0f5052ea-7158-11e8-81a4-cad0c67934d7.png">

**Comment by jawsvk** [comment]
Seems like an error parsing text to date format. In order to standardize, i am changing the datepicker format on homepage to fit gabriel's at booking page. I have also made the necessary changes in booking controller to parse "dd/MM/yyyy" .

please try again after someone review my pull request from today

**Comment by natebakescakes** [comment]
Fixed by PR #51
